name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build project
        run: dotnet build --configuration Release wifi\ qr\ generator\wifi\ qr\ generator.csproj

      - name: Publish executable
        run: dotnet publish --configuration Release --output ./publish wifi\ qr\ generator\wifi\ qr\ generator.csproj

      - name: Create standalone executable
        run: |
          cd publish
          dotnet publish -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true wifi\ qr\ generator\wifi\ qr\ generator.csproj

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload standalone executable
        uses: actions/upload-artifact@v2
        with:
          name: Standalone Executable
          path: publish/bin/Release/net6.0/win-x64/publish/*.exe

      - name: Attach artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/publish/bin/Release/net6.0/win-x64/publish/*.exe
          asset_name: standalone-executable.exe
          asset_content_type: application/octet-stream
